name: Build and Test Docker

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build Docker image
        run: docker build -t hf-sentimentanalysis .

      - name: Run container and test endpoint
        run: |
          docker run -d --name test-hf-app -p 7860:7860 hf-sentimentanalysis
          sleep 10
          curl --fail -X POST -H "Content-Type: application/json" -d '{"text": "I love Hugging Face!"}' http://localhost:7860/predict || (docker logs test-hf-app && exit 1)

      - name: Add Hugging Face remote
        env:
          HF: ${{ secrets.HF }}
        run: |
          git remote add space https://oauth2:$HF@huggingface.co/spaces/MohamedMoustafa/hf-sentimentanalysis || echo "Remote exists"

      - name: Push to Hugging Face Space
        env:
          HF: ${{ secrets.HF }}
        run: git push --force space main