name: Build and Test Docker

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build Docker image
        run: docker build -t hf-sentimentanalysis .

      - name: Run container and test endpoint
        run: |
          docker run -d --name test-hf-app -p 7860:7860 hf-sentimentanalysis
          sleep 10
          curl --fail -X POST -H "Content-Type: application/json" -d '{"text": "I love Hugging Face!"}' http://localhost:7860/predict || (docker logs test-hf-app && exit 1)